'use strict';
/**
 * Resolves which data files the CLI reads.
 *
 * Two tiers, deliberately separated:
 *   - SEED files are committed. data/sequence-template.json is generated by
 *     tools/build-sequence.mjs and config/settings.json holds safe defaults.
 *   - LIVE files are written by tools/assemble.mjs from the console's database
 *     and are gitignored. They are this machine's copy of what the operator actually
 *     edited, and they win whenever present.
 *
 * Keeping them apart means the daily job can never dirty a committed file, and
 * CI can prove the committed sequence still matches its builder.
 */
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');

const TIERS = {
  settings: { live: 'config/settings-live.json', seed: 'config/settings.json' },
  sequence: { live: 'data/sequence-live.json', seed: 'data/sequence-template.json' },
};

function resolve(root, tier) {
  const live = path.join(root, TIERS[tier].live);
  return fs.existsSync(live)
    ? { file: live, tier: 'live' }
    : { file: path.join(root, TIERS[tier].seed), tier: 'seed' };
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/** Load everything the CLI needs, reporting which tier each file came from. */
function load(root = ROOT) {
  const settingsSrc = resolve(root, 'settings');
  const sequenceSrc = resolve(root, 'sequence');
  const settings = readJson(settingsSrc.file);
  const sequence = readJson(sequenceSrc.file);
  const prospects = readJson(path.join(root, 'data/prospects.json')).prospects || [];
  const packs = readJson(path.join(root, 'data/play-packs.json')).packs || [];
  const packById = Object.fromEntries(packs.map((p) => [p.id, p]));
  return {
    settings, sequence, prospects, packs, packById,
    sources: { settings: settingsSrc, sequence: sequenceSrc },
  };
}

module.exports = { load, resolve, ROOT, TIERS };
